language: c
notifications:
    irc: "chat.freenode.net#krebs_incoming"
    on_success: change
    on_failure: always
script: "! ( make -C util test | grep -q '^not ok' )"
before_install:
  - sudo apt-get install bc -qq
  - sudo apt-get install python -qq
  - sudo apt-get install w3m -qq
branches:
    only:
        - master
git:
    submodules: false
